# Generated by Django 5.2.4 on 2025-10-23 13:21

import django.db.models.deletion
import mediafiles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='media',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='owner',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=mediafiles.models.upload_to_media),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
